### ISSUE TITLE
用fragement里显示。共四张图循环，每次最后一张图是空白，请问咋处理呀？

### ISSUE THREAD

**Issue by hanfeng1982** [androiddevelop/CycleViewPager#4]
List<View> views = new ArrayList<View>();
         ImageView iv0 = new ImageView(getActivity().getApplicationContext());
        iv0.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image0));
        ImageView iv1 = new ImageView(getActivity().getApplicationContext());
        iv1.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image1));
        ImageView iv2 = new ImageView(getActivity().getApplicationContext());
        iv2.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image2));
        ImageView iv3 = new ImageView(getActivity().getApplicationContext());
        iv3.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image3));

        views.add(iv3);
        views.add(iv0);
        views.add(iv1);
        views.add(iv2);
        views.add(iv3);
        views.add(iv0);
        CycleViewPager cycleViewPager =fragmentTuijianBinding.cycleViewPager;
         //循环+轮播，3000ms自动切换
        cycleViewPager.setData(views, true, true, 3000);

**Comment by Fessible** [comment]
你不能复用 iv3和iv0，每个view要单独创建一个
也就是
ImageView iv02 = new ImageView(getActivity().getApplicationContext());
iv02.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image0));
ImageView iv0 = new ImageView(getActivity().getApplicationContext());
iv0.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image0));
ImageView iv1 = new ImageView(getActivity().getApplicationContext());
iv1.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image1));
ImageView iv2 = new ImageView(getActivity().getApplicationContext());
iv2.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image2));
ImageView iv3 = new ImageView(getActivity().getApplicationContext());
iv3.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image3));
ImageView iv32 = new ImageView(getActivity().getApplicationContext());
iv32.setImageBitmap(BitmapFactory.decodeResource(getResources(),R.drawable.image3));
    views.add(iv32);
    views.add(iv0);
    views.add(iv1);
    views.add(iv2);
    views.add(iv3);
    views.add(iv02);

**Comment by androiddevelop** [comment]
一个view只能有一个parent，所以复用的前提是两个view不能挨着，挨着的话切换的时候会有问题
